---
namespace: main
description: main
repository: https://github.com/e-gautier/dotfiles
name: dotfiles
version: 1.0.0
readme: README.md
authors:
  - etienne
dependencies:
  "community.general": "*"
  "community.crypto": "*"
  "ansible.posix": "*"
