# ansible-galaxy install -r galaxy-roles.yml
# ansible-playbook -K playbook.yml
---
- name: Dotfiles
  connection: local
  hosts: localhost
  vars_prompt: []
  tasks:
    - name: Assert version
      ansible.builtin.assert:
        that: ansible_version.full is version(ansible_core_version, '>=')
        success_msg: "Ansible version >= {{ ansible_core_version }}"
        fail_msg: "Ansible version < {{ ansible_core_version }}"
      vars:
        ansible_core_version: 2.12
    - name: Include Linux role
      ansible.builtin.import_role:
        name: linux
      when: ansible_facts["system"] == "Linux"
