set history=900

filetype plugin on
filetype indent on
syntax on

" subfolders search and tab completion
set path+=**

" display matching file list on tab
set wildmenu

" update file is modified
set autoread

" search
set ignorecase
set smartcase
set incsearch
set hlsearch
set magic

" brackets
set showmatch

" colors
set background=dark

" tab
set expandtab
set shiftwidth=2
set tabstop=2

" line width limit
set colorcolumn=120

" Return to last edit position when opening files
autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif

" viminfo keeping
set viminfo=%,<800,'10,/50,:100,h
set laststatus=2

" Airline theme
let g:airline_theme = 'codedark'

set number
set showcmd
set mouse=a
set lazyredraw

" Load Pathogen
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
let g:indent_guides_enable_on_vim_startup = 1

" autorun ColorHighlight after bundles load
autocmd VimEnter * ColorHighlight

" colorsheme from https://github.com/tomasiser/vim-code-dark
colorscheme codedark
" override search highlight color
hi Search ctermfg=black ctermbg=yellow

" tmuxline disable arrow separators
let g:tmuxline_powerline_separators = 0

" allow to save with sudo
cmap w!! w !sudo tee > /dev/null %

" always focus to file opened
let g:nerdtree_tabs_open_on_gui_startup = 2

" NERDTree tab support
let g:nerdtree_tabs_open_on_console_startup = 1

" focus opened window
let g:nerdtree_tabs_smart_startup_focus = 2

" command shortcut to fzf
map <S-C-a> :FZF<Enter>

" enable auto save
let g:auto_save = 1

" enable common shortcut
source $VIMRUNTIME/mswin.vim
behave mswin

" smoothscroll
noremap <silent> <c-u> :call smooth_scroll#up(&scroll, 0, 2)<CR>
noremap <silent> <c-d> :call smooth_scroll#down(&scroll, 0, 2)<CR>
noremap <silent> <c-b> :call smooth_scroll#up(&scroll*2, 0, 4)<CR>
noremap <silent> <c-f> :call smooth_scroll#down(&scroll*2, 0, 4)<CR>

