---
- name: Install dnf plugins-core
  ansible.builtin.package:
    name: dnf-plugins-core
    state: present
- name: Install Docker repo
  ansible.builtin.command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
  register: output
  changed_when: output.rc != 0
- name: Install Docker
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
- name: Restart Docker service
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
    daemon_reload: true
  loop:
    - docker
    - containerd
  register: output
  changed_when: output.state != "started"
