---
- name: dnf.plugins-core
  package:
    name: dnf-plugins-core
    state: present
- name: docker.repo
  shell: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
- name: docker.install
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
- name: docker.service
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  loop:
      - docker
      - containerd
