---
- name: Install Nftables
  become: true
  ansible.builtin.package:
    name: nftables
- name: Setup nft.inet.filter rules
  ansible.builtin.copy:
    src: "{{ role_path }}/files/nftables/inet-filter.nft"
    dest: /etc/nftables/inet-filter.nft
- name: Enable nft inet.filter rules
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/nftables.conf
    regexp: ^# include "\/etc\/nftables\/inet\-filter.nft"$
    line: include "/etc/nftables/inet-filter.nft"
- name: Restart nft service
  ansible.builtin.systemd:
    name: nftables
    state: restarted
    enabled: true
    daemon_reload: true
  register: output
  changed_when: output.state != "started"
