---
- name: dnf.security.install
  package:
    name: dnf-automatic
    state: present
- name: dnf.security.configure
  replace:
    path: /etc/dnf/automatic.conf
    regexp: "{{ item.key }}"
    replace: "{{ item.value }}"
  loop: "{{ items | dict2items }}"
  vars:
    items:
      upgrade_type = default: upgrade_type = security
      apply_updates = no: apply_updates = yes
- name: dnf.security.service
  systemd:
    name: dnf-automatic.timer
    state: restarted
    enabled: yes
    daemon_reload: yes
