---
- name: Install dnf security auto updates
  ansible.builtin.package:
    name: dnf-automatic
    state: present
- name: Configure dnf security auto update
  ansible.builtin.replace:
    path: /etc/dnf/automatic.conf
    regexp: "{{ item.key }}"
    replace: "{{ item.value }}"
  loop: "{{ items | dict2items }}"
  vars:
    items:
      upgrade_type = default: upgrade_type = security
      apply_updates = no: apply_updates = yes
- name: Restart dnf security service
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    state: restarted
    enabled: true
    daemon_reload: true
  register: output
  changed_when: output.state != "started"
