---
- name: vimyoucompleteme.dependencies
  become: yes
  package:
    name:
      - cmake
      - g++
      - python3-devel
    state: present
- name: vimyoucompleteme.install
  shell:
    cmd: "{{ playbook_dir }}/vim/bundle/youcompleteme/install.py"
