---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: instance
    box: fedora/37-cloud-base
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../roles"
    ANSIBLE_CONFIG: "../../ansible.cfg"
    ANSIBLE_PLAYBOOK_DIR: "../.."
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
