---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Services facts loading
      ansible.builtin.service_facts:
    - name: Assert required services are enabled
      ansible.builtin.assert:
        that:
          - ansible_facts.services["systemd-resolved.service"]["status"] == "enabled"
