---
- name: Verify
  hosts: all
  tasks:
    - name: Assert git config symlink exists
      ansible.builtin.stat:
        path: ~/.gitconfig
      register: gitconfig
    - name: Verify gitconfig is a symlink
      ansible.builtin.assert:
        that:
          - gitconfig.stat.exists
          - gitconfig.stat.islnk
