set history=10000

syntax on

" update file is modified
set autoread
" map ; to reload buffer
nmap ; :e <Enter>
" notify on buffer reload
autocmd FileChangedShellPost *
    \ echohl WarningMsg | echo "File changed on disk. Buffer reloaded." | echohl None

" search
set ignorecase
set smartcase
set incsearch
set hlsearch

" tab
set expandtab
set shiftwidth=4
set tabstop=4

" line width limit
set colorcolumn=100

set number
set showcmd
set mouse=a

" persistent hitory
set undofile
set undodir=~/.vim/undodir

" Return to last edit position when opening files
autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif

" vim statusbar
set laststatus=2

" Lightline theme
let g:lightline = {"colorscheme": "deus"}

" Load Pathogen
let g:pathogen_disabled = ["vim-sensible"]
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

" disable format options
set formatoptions=

" disable auto indent
filetype indent off
set autoindent&
set cindent&
set smartindent&
set indentexpr&

" indent visual indicator
let g:indent_guides_enable_on_vim_startup = 1

" autorun ColorHighlight after bundles load
autocmd VimEnter * ColorHighlight

" colorsheme from https://github.com/tomasiser/vim-code-dark
colorscheme codedark

" override search highlight color
hi Search ctermfg=black ctermbg=yellow

" allow to save with sudo
cmap w!! w !sudo tee > /dev/null %

" enable auto save
let g:auto_save = 1

" smoothscroll
noremap <silent> <c-u> :call smooth_scroll#up(&scroll, 0, 2)<CR>
noremap <silent> <c-d> :call smooth_scroll#down(&scroll, 0, 2)<CR>
noremap <silent> <c-b> :call smooth_scroll#up(&scroll*2, 0, 4)<CR>
noremap <silent> <c-f> :call smooth_scroll#down(&scroll*2, 0, 4)<CR>

" FZF shortcut
nmap , :Files <Enter>

" Nerdtree hidden files
let NERDTreeShowHidden=1

" move line up/down shortcuts
map <C-k> :m-2 <Enter>
map <C-j> :m+1 <Enter>

