export ZSH="$HOME/.oh-my-zsh"
plugins=(git colored-man-pages colorize)
source $ZSH/oh-my-zsh.sh
CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
COMPLETION_WAITING_DOTS="%F{yellow}searching...%f"
HIST_STAMPS="dd/mm/yyyy"
zstyle ':completion:*:default' menu search
zstyle ':completion:*:default' list-colors
source ~/.bashrc
PS1='%n@%M:%~$(__git_ps1 " [%s] ")[$?]\$ '

