case $- in
    *i*) ;;
      *) return;;
esac

HISTCONTROL=ignoreboth
HISTSIZE=-1
HISTFILESIZE=-1
HISTTIMEFORMAT="%F %T "

# aliases
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# locales
if [ -f ~/.profile  ]; then
    . ~/.profile
fi

# profile directory
if [ -d ~/.profile.d ]; then
    for file in ~/.profile.d/*; do source $file; done
fi

# local bin
PATH=$PATH:~/.local/bin:~/.bin

# umask
umask 0077

# caps lock to esc remapping
if [ -x "$(command -v setxkbmap)" ]; then
   setxkbmap -option caps:swapescape
fi

PROMPT_COMMAND=prompt

prompt() {
  # git integrated in PS1
  PS1='\u@\h:\w$(__git_ps1 " [%s] ")[$?]\$ '

  # save history at each prompt
  PROMPT_COMMAND="history -a;$PROMPT_COMMAND"
}

# enable forward search with ctrl s
stty -ixon

